spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security-tutorial?reWriteBatchedInserts=true
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
          lob:
            non_contextual_creation: true

security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me